repository:
  name: spectral-goat
  enable_vulnerability_alerts: false

collaborators:
  - username: barlesh
    permission: admin
  - username: ChengaDev
    permission: admin
  - username: guylev008
    permission: admin

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        require_code_owner_reviews: false
        required_approving_review_count: 1
        dismissal_restrictions:
          users:
          - ChengaDev
          - njenia
          teams:
          - backend
          - infrastructure
      allow_force_pushes: 
        enabled: true

  - name: feature-branch-1
    protection:
      allow_force_pushes: 
        enabled: true
  - name: feature-branch-2
    protection:
  - name: feature-branch-3
